### ISSUE TITLE
issue with new line in msg to slack 

### ISSUE THREAD

**Issue by hvdbunte** [ptarmiganlabs/butler#45]
Hi,

Thanks for this add-on for the Slack integration. 

I am new to this, so maybe it is an issue but maybe my code is not correct. But when I try to put in a new line in the message by using \n. The \n is just shown as text. 

I tried the send.slack command from the node.slack on it's own and then it works. 

Can you let me know if it is possible to add a new line in the Slack message or what I can do to fix this? 

Thanks

**Comment by mountaindude** [comment]
Old, old message this. Probably not an issue any more.

Anyways, adding `\n`usually does the trick. But depending on whether the field in question is text or something else, you could also try with `\\n`.

Lots and lots of changes in Butler since this issue was created, so hopefully it's not even an issue any more.
Closing it for now, please feel free to reopen if needed.
