### ISSUE TITLE
Version 9.4.0 doesn't run and doesn't throw any errors

### ISSUE THREAD

**Issue by USBWAG** [ptarmiganlabs/butler#936]
### What version of Butler are you using?

butler Version 9.4.0

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler.

node version v18.17.1

### What command did you use to start Butler?

node src\butler.js -c prod.yaml | butler.exe -c prod.yaml | butler -prod.yaml

### What operating system are you using?

Windows 10

### What CPU architecture are you using?

x64

### What Qlik Sense versions are you using?

Qlik Sense May 2022 Patch 3

### Describe the Bug

Hi Goran
I have a problem with the latest version of Butler 9.4.0
If I run it no matter exe or nodejs file.

Once the value
anonTelemetry: false

It simply aborts and gives no error message no matter what log level 
# Log level. Possible log levels are silly, debug, verbose, info, warn, error
i have try all LOG Levels

![image](https://github.com/ptarmiganlabs/butler/assets/86729881/46b44eb8-bf7a-4ce3-8617-cf6592dbec5c)

is the value
anonTelemetry: true

It doesn't abort, but the task messages whether abort or something else no longer come. No matter what kind of termination, nothing will be communicated and nothing will be visible in the LOG

![image](https://github.com/ptarmiganlabs/butler/assets/86729881/6a5c7a6c-289c-4d47-8ede-21b30539fcce)

### Expected Behavior

That at least it throws error messages

### To Reproduce

It should be reproducible, just switch the value "anonTelemetry: true" to false and see if it stops immediately for you.

**Comment by USBWAG** [comment]
Good evening

I just wanted to let you know that I had previously used version 9.2, and it worked without any problems. I skipped version 9.3.

I noticed that you switched to Node 20 in version 9.4.0, which I also installed to test it.
In the exe it automatically refers to version Node version 18, in the source I could try it with version 20 and the same problem. 
![image](https://github.com/ptarmiganlabs/butler/assets/86729881/5eb75755-305e-40dc-8691-d72a4afd33e2)
As soon as the telemetry is activated again, it remains running, but I no longer receive any abort messages.

I'll go through version 9.3 tomorrow and see how it behaves there.

**Comment by mountaindude** [comment]
Good work finding and isolating this bug, I will try to dig into it during coming days.

There was indeed a switch from older Node versions in latest Butler release, and it seems all platform/parameter variants were not fully covered by test cases.
That's a challenge in itself with complex software - the number of test cases just explodes when features, platforms etc are added... But that's just how things are, of course :)

**Comment by USBWAG** [comment]
Hello Mr. Mountaindude

So I did a few more tests and experiments over the weekend. And now version 9.4.0 is running
I moved from version 9.2. fought through every version. 9.3 after the new config they had no problem starting or anything else. But version 9.4. had problems.

I then played around with influx Settings and tried them out, but it didn't help either. 
What helped me was to drop the Influx and then start it again. After that it went without any problems.

The problem that occurs when telemetry is switched on or off no longer causes problems.

But at the moment I can't figure out why it simply shut down before without any error message.
I still don't fully understand why I had to do a DB drop for myself.

If you want, I'll try to reproduce it again. in which I run version 9.2 and then 9.4. (Next week)
Currently I can switch between the versions without any problems

Just one more piece of information, the 9.4. Exe binary is still on Node 18, but I now have exe and nodejs running without any problems

Otherwise you can close this here :)

**Comment by mountaindude** [comment]
Thanks again for investigating this.

I suspect the problems you experienced were due to a minor change in the structure of the InfluxDB database that Butler uses.
Version 9.4.0 added a bit of information to that database, probably causing problems. I've seen it too and others have mentioned similar things.

The solution is pretty easy though: Just delete the InfluxDB database before starting the new Butler version. 
For example, if my InfluxDB database is called "butlerops" I would do something like this:

```bash
influx --host <ip-where-influxdb-is-running> --port <influxdb-port-usually-8086>
drop database butlerops
exit
```

The above has worked for me and I have not been able to reproduce any errors when first dropping the db.

Regarding the different Node versions... 
Creating binaries from Node.js has always been somewhat of a mess. 
Still, it's much easier to use a binary pre-compiled for your OS than first installing Node.js etc.

Butler (and [Butler SOS](https://butler-sos.ptarmiganlabs.com), [Butler Sheet Icons](https://github.com/ptarmiganlabs/butler-sheet-icons), [Ctrl-Q](https://ctrl-q.ptarmiganlabs.com) etc) all use the same tool for creating binaries: [pkg](https://github.com/vercel/pkg).

Now, pkg is sunset as of a week ago.
No immediate issue for the Butler tools, but they will need to be migrated to some new, better, shinier tool.
Not a problem, but a little heads up that focus will be on that during coming weeks or months.
Not sure yet how much work is involved (have not yet decided which of several options to go with).

All in all, just another turn in the life of software development :)
